image: maven:latest

stages:
  - build
  - run


cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

run:
  stage: run
  script:
    - mvn package
    - java -Dexec.mainClass="com.dzl.myblog.MyblogApplication"