package com.dzl.myblog.entity;

public class ArticleTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.tagName
     *
     * @mbg.generated
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.tagSize
     *
     * @mbg.generated
     */
    private Integer tagSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.id
     *
     * @return the value of article_tag.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.id
     *
     * @param id the value for article_tag.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.tagName
     *
     * @return the value of article_tag.tagName
     *
     * @mbg.generated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.tagName
     *
     * @param tagName the value for article_tag.tagName
     *
     * @mbg.generated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.tagSize
     *
     * @return the value of article_tag.tagSize
     *
     * @mbg.generated
     */
    public Integer getTagSize() {
        return tagSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.tagSize
     *
     * @param tagSize the value for article_tag.tagSize
     *
     * @mbg.generated
     */
    public void setTagSize(Integer tagSize) {
        this.tagSize = tagSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ArticleTag other = (ArticleTag) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTagName() == null ? other.getTagName() == null : this.getTagName().equals(other.getTagName()))
            && (this.getTagSize() == null ? other.getTagSize() == null : this.getTagSize().equals(other.getTagSize()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTagName() == null) ? 0 : getTagName().hashCode());
        result = prime * result + ((getTagSize() == null) ? 0 : getTagSize().hashCode());
        return result;
    }
}