package com.dzl.myblog.entity;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleId
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.originalAuthor
     *
     * @mbg.generated
     */
    private String originalAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleTitle
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleTags
     *
     * @mbg.generated
     */
    private String articleTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleType
     *
     * @mbg.generated
     */
    private String articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleCategories
     *
     * @mbg.generated
     */
    private String articleCategories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.publishDate
     *
     * @mbg.generated
     */
    private String publishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updateDate
     *
     * @mbg.generated
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleUrl
     *
     * @mbg.generated
     */
    private String articleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.likes
     *
     * @mbg.generated
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.lastArticleId
     *
     * @mbg.generated
     */
    private Long lastArticleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.nextArticleId
     *
     * @mbg.generated
     */
    private Long nextArticleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleId
     *
     * @return the value of article.articleId
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleId
     *
     * @param articleId the value for article.articleId
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.originalAuthor
     *
     * @return the value of article.originalAuthor
     *
     * @mbg.generated
     */
    public String getOriginalAuthor() {
        return originalAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.originalAuthor
     *
     * @param originalAuthor the value for article.originalAuthor
     *
     * @mbg.generated
     */
    public void setOriginalAuthor(String originalAuthor) {
        this.originalAuthor = originalAuthor == null ? null : originalAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleTitle
     *
     * @return the value of article.articleTitle
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleTitle
     *
     * @param articleTitle the value for article.articleTitle
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleTags
     *
     * @return the value of article.articleTags
     *
     * @mbg.generated
     */
    public String getArticleTags() {
        return articleTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleTags
     *
     * @param articleTags the value for article.articleTags
     *
     * @mbg.generated
     */
    public void setArticleTags(String articleTags) {
        this.articleTags = articleTags == null ? null : articleTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleType
     *
     * @return the value of article.articleType
     *
     * @mbg.generated
     */
    public String getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleType
     *
     * @param articleType the value for article.articleType
     *
     * @mbg.generated
     */
    public void setArticleType(String articleType) {
        this.articleType = articleType == null ? null : articleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleCategories
     *
     * @return the value of article.articleCategories
     *
     * @mbg.generated
     */
    public String getArticleCategories() {
        return articleCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleCategories
     *
     * @param articleCategories the value for article.articleCategories
     *
     * @mbg.generated
     */
    public void setArticleCategories(String articleCategories) {
        this.articleCategories = articleCategories == null ? null : articleCategories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.publishDate
     *
     * @return the value of article.publishDate
     *
     * @mbg.generated
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.publishDate
     *
     * @param publishDate the value for article.publishDate
     *
     * @mbg.generated
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updateDate
     *
     * @return the value of article.updateDate
     *
     * @mbg.generated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updateDate
     *
     * @param updateDate the value for article.updateDate
     *
     * @mbg.generated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleUrl
     *
     * @return the value of article.articleUrl
     *
     * @mbg.generated
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleUrl
     *
     * @param articleUrl the value for article.articleUrl
     *
     * @mbg.generated
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl == null ? null : articleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.likes
     *
     * @return the value of article.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.likes
     *
     * @param likes the value for article.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.lastArticleId
     *
     * @return the value of article.lastArticleId
     *
     * @mbg.generated
     */
    public Long getLastArticleId() {
        return lastArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.lastArticleId
     *
     * @param lastArticleId the value for article.lastArticleId
     *
     * @mbg.generated
     */
    public void setLastArticleId(Long lastArticleId) {
        this.lastArticleId = lastArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.nextArticleId
     *
     * @return the value of article.nextArticleId
     *
     * @mbg.generated
     */
    public Long getNextArticleId() {
        return nextArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.nextArticleId
     *
     * @param nextArticleId the value for article.nextArticleId
     *
     * @mbg.generated
     */
    public void setNextArticleId(Long nextArticleId) {
        this.nextArticleId = nextArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Article other = (Article) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getOriginalAuthor() == null ? other.getOriginalAuthor() == null : this.getOriginalAuthor().equals(other.getOriginalAuthor()))
            && (this.getArticleTitle() == null ? other.getArticleTitle() == null : this.getArticleTitle().equals(other.getArticleTitle()))
            && (this.getArticleTags() == null ? other.getArticleTags() == null : this.getArticleTags().equals(other.getArticleTags()))
            && (this.getArticleType() == null ? other.getArticleType() == null : this.getArticleType().equals(other.getArticleType()))
            && (this.getArticleCategories() == null ? other.getArticleCategories() == null : this.getArticleCategories().equals(other.getArticleCategories()))
            && (this.getPublishDate() == null ? other.getPublishDate() == null : this.getPublishDate().equals(other.getPublishDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getArticleUrl() == null ? other.getArticleUrl() == null : this.getArticleUrl().equals(other.getArticleUrl()))
            && (this.getLikes() == null ? other.getLikes() == null : this.getLikes().equals(other.getLikes()))
            && (this.getLastArticleId() == null ? other.getLastArticleId() == null : this.getLastArticleId().equals(other.getLastArticleId()))
            && (this.getNextArticleId() == null ? other.getNextArticleId() == null : this.getNextArticleId().equals(other.getNextArticleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getOriginalAuthor() == null) ? 0 : getOriginalAuthor().hashCode());
        result = prime * result + ((getArticleTitle() == null) ? 0 : getArticleTitle().hashCode());
        result = prime * result + ((getArticleTags() == null) ? 0 : getArticleTags().hashCode());
        result = prime * result + ((getArticleType() == null) ? 0 : getArticleType().hashCode());
        result = prime * result + ((getArticleCategories() == null) ? 0 : getArticleCategories().hashCode());
        result = prime * result + ((getPublishDate() == null) ? 0 : getPublishDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getArticleUrl() == null) ? 0 : getArticleUrl().hashCode());
        result = prime * result + ((getLikes() == null) ? 0 : getLikes().hashCode());
        result = prime * result + ((getLastArticleId() == null) ? 0 : getLastArticleId().hashCode());
        result = prime * result + ((getNextArticleId() == null) ? 0 : getNextArticleId().hashCode());
        return result;
    }
}