package com.dzl.myblog.entity;

public class ArticleWithBLOBs extends Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleContent
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleTabloid
     *
     * @mbg.generated
     */
    private String articleTabloid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleContent
     *
     * @return the value of article.articleContent
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleContent
     *
     * @param articleContent the value for article.articleContent
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleTabloid
     *
     * @return the value of article.articleTabloid
     *
     * @mbg.generated
     */
    public String getArticleTabloid() {
        return articleTabloid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleTabloid
     *
     * @param articleTabloid the value for article.articleTabloid
     *
     * @mbg.generated
     */
    public void setArticleTabloid(String articleTabloid) {
        this.articleTabloid = articleTabloid == null ? null : articleTabloid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ArticleWithBLOBs other = (ArticleWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getOriginalAuthor() == null ? other.getOriginalAuthor() == null : this.getOriginalAuthor().equals(other.getOriginalAuthor()))
            && (this.getArticleTitle() == null ? other.getArticleTitle() == null : this.getArticleTitle().equals(other.getArticleTitle()))
            && (this.getArticleTags() == null ? other.getArticleTags() == null : this.getArticleTags().equals(other.getArticleTags()))
            && (this.getArticleType() == null ? other.getArticleType() == null : this.getArticleType().equals(other.getArticleType()))
            && (this.getArticleCategories() == null ? other.getArticleCategories() == null : this.getArticleCategories().equals(other.getArticleCategories()))
            && (this.getPublishDate() == null ? other.getPublishDate() == null : this.getPublishDate().equals(other.getPublishDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getArticleUrl() == null ? other.getArticleUrl() == null : this.getArticleUrl().equals(other.getArticleUrl()))
            && (this.getLikes() == null ? other.getLikes() == null : this.getLikes().equals(other.getLikes()))
            && (this.getLastArticleId() == null ? other.getLastArticleId() == null : this.getLastArticleId().equals(other.getLastArticleId()))
            && (this.getNextArticleId() == null ? other.getNextArticleId() == null : this.getNextArticleId().equals(other.getNextArticleId()))
            && (this.getArticleContent() == null ? other.getArticleContent() == null : this.getArticleContent().equals(other.getArticleContent()))
            && (this.getArticleTabloid() == null ? other.getArticleTabloid() == null : this.getArticleTabloid().equals(other.getArticleTabloid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getOriginalAuthor() == null) ? 0 : getOriginalAuthor().hashCode());
        result = prime * result + ((getArticleTitle() == null) ? 0 : getArticleTitle().hashCode());
        result = prime * result + ((getArticleTags() == null) ? 0 : getArticleTags().hashCode());
        result = prime * result + ((getArticleType() == null) ? 0 : getArticleType().hashCode());
        result = prime * result + ((getArticleCategories() == null) ? 0 : getArticleCategories().hashCode());
        result = prime * result + ((getPublishDate() == null) ? 0 : getPublishDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getArticleUrl() == null) ? 0 : getArticleUrl().hashCode());
        result = prime * result + ((getLikes() == null) ? 0 : getLikes().hashCode());
        result = prime * result + ((getLastArticleId() == null) ? 0 : getLastArticleId().hashCode());
        result = prime * result + ((getNextArticleId() == null) ? 0 : getNextArticleId().hashCode());
        result = prime * result + ((getArticleContent() == null) ? 0 : getArticleContent().hashCode());
        result = prime * result + ((getArticleTabloid() == null) ? 0 : getArticleTabloid().hashCode());
        return result;
    }
}