package com.dzl.myblog.entity;

public class Visitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visitorNum
     *
     * @mbg.generated
     */
    private Long visitorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.pageName
     *
     * @mbg.generated
     */
    private String pageName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.id
     *
     * @return the value of visitor.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.id
     *
     * @param id the value for visitor.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visitorNum
     *
     * @return the value of visitor.visitorNum
     *
     * @mbg.generated
     */
    public Long getVisitorNum() {
        return visitorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visitorNum
     *
     * @param visitorNum the value for visitor.visitorNum
     *
     * @mbg.generated
     */
    public void setVisitorNum(Long visitorNum) {
        this.visitorNum = visitorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.pageName
     *
     * @return the value of visitor.pageName
     *
     * @mbg.generated
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.pageName
     *
     * @param pageName the value for visitor.pageName
     *
     * @mbg.generated
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Visitor other = (Visitor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVisitorNum() == null ? other.getVisitorNum() == null : this.getVisitorNum().equals(other.getVisitorNum()))
            && (this.getPageName() == null ? other.getPageName() == null : this.getPageName().equals(other.getPageName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVisitorNum() == null) ? 0 : getVisitorNum().hashCode());
        result = prime * result + ((getPageName() == null) ? 0 : getPageName().hashCode());
        return result;
    }
}