package com.dzl.myblog.mapper;

import com.dzl.myblog.entity.Visitor;
import com.dzl.myblog.entity.VisitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    long countByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int deleteByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int insert(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int insertSelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    List<Visitor> selectByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    Visitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Visitor record);
}